FROM python:3.8.5-alpine3.12

LABEL maintainer="Raben Shrestha"

WORKDIR /app

EXPOSE 5000
ENV FLASK_APP=app.py

COPY ./backend/app /app
RUN pip install -r requirements.txt

# ENTRYPOINT [ "flask"]
CMD ["flask", "run", "-h", "0.0.0.0", "-p", "5000"]