version: "3.7"
services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        # volumes:
        #     - '.:/app'
        #     - '/app/node_modules'
        ports:
          - 3000:3000
    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        ports:
            - 5000: 5000
        volumes:
            -.:/backend